default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['host_postgres'] %>
  port: <%= ENV['port_postgres'] %>
  username: <%= ENV['username_postgres'] %>
  password: <%= ENV['password_postgres'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: animes_development

test:
  <<: *default
  database: animes_test

production:
  <<: *default
  database: animes_production
  username: animes
  password: <%= ENV['ANIMES_DATABASE_PASSWORD'] %>
